### ISSUE TITLE
Shortcut function this.$fb.track() is not working

### ISSUE THREAD

**Issue by HapLifeMan** [WilliamDASILVA/nuxt-facebook-pixel-module#6]
**Describe the bug**
The shortcut function `this.$fb.track()` is not working.

**To Reproduce**
1. Call `this.$fb.track('Lead')` for example
2. See that no event is sent with Facebook Pixel Helper extension
3. By the way `this.$fb.query('track', 'Lead')` is working fine

**Expected behavior**
It is expected that an event is sent.

**Desktop (please complete the following information):**
 - OS: max OS High Sierra
 - Browser: Safari or Chrome
 - Version: latests

**Additional context**
Thanks 😊

**Comment by WilliamDASILVA** [comment]
@HapLifeMan Hello,

Thank you for reporting this issue!
I'll take a look at it very soon and keep you updated when it's fixed. ❤️

**Comment by WilliamDASILVA** [comment]
Hello @HapLifeMan,

Sorry for the delay, just tested the `$fb.track` method and **it worked as expected**, by calling the `$fb.query` method.

```js
 export default {
   mounted () {
     this.$fb.track()
   }
 }
```

If you use the `$fb.track()` without any parameter, it does a `query('track', 'PageEvent')` since the default `track` value is 'PageView'; that can be override in the options.

Could you take a look again and report me if you're still experiencing this issue and I'll be glad to check it for you.

Thanks again for taking the time to report this issue!

**Comment by roryheaney** [comment]
@WilliamDASILVA does `this.$fb.track()` need to be added to each page or does the module fire that automatically through the router change?

**Comment by PuxianAlHazred** [comment]
up ... doesn't works for me 
> Échec du chargement pour l’élément <script> dont la source est « https://connect.facebook.net/en_US/fbevents.js ».

**Comment by Torone** [comment]
`this.$fb.track('Lead')`

> TypeError: this.$fb.track is not a function

`this.$fb.query('track', 'Lead')`

> TypeError: this.$fb.query is not a function

Any clue how to let it work?

My nuxt config is:

```
    ['nuxt-facebook-pixel-module', {
      pixelId: my_id',
      track: 'PageView',
      disabled: false
    }],
```

**Comment by WilliamDASILVA** [comment]
@roryheaney The track event is fired only on the page load.
A router middleware was added to automatically triggers the 'PageView' on route change. See https://github.com/WilliamDASILVA/nuxt-facebook-pixel-module/issues/20

Otherwise, the OP issue could not be reproduced. If you still experience this issue, let me know.
